### PR TITLE
Reviews ratings

### PR DESCRIPTION
**Pull request by farhanali3193**

### CODE REVIEW

**Comment by farhanali3193** [comment]
Wrote dummy tests. Will have to refactor them once I figure out how to implement sort along with filter functionality

**Comment by farhanali3193** [comment]
1. Sort + Filter working fine. Will refactor the code later to make it cleaner.

**Comment by farhanali3193** [comment]
1. Created route for getting meta data.
2. Dynamically rendering range meaning. (too small for Size while poor for Quality ).
3. CSS and alignments might be a little off. Will fix them after finishing the entire widget's functionality

**Comment by carrjsn** [comment]
Sorry I didn't realize I committed the product_id change. Thanks for changing it back. I was using a different one for testing multiple style images. All looks good

**Pull request merged**
