### PR TITLE
Reviews tile: Getting data from API

### PR DESCRIPTION
**Pull request by farhanali3193**

### CODE REVIEW

**Comment by farhanali3193** [comment]
@carrjsn @EvanN148 @sudhakg 
1. Added eslint rule for backticks.
2. Getting list of reviews  from Atelier API.
3. Added dummy Search component.
4. Added axios.
5. Added a GET/reviews route in server.

**Review by carrjsn — COMMENTED** [review]
Hey Han, just a quick question about the GIT_TOKEN. I noticed on line 17 of index.js you have a different process.env variable for your API key. We had previously defined gitToken on line 5. Shouldn't we be using that for our API calls instead of making separate environment variables? I'm totally happy to change line 5 to be process.env.GITHUB_TOKEN instead. It just seems like we would want to be consistent whatever it is. Unless I'm missing something. Let me know what you think.

**Comment by farhanali3193** [comment]
> Hey Han, just a quick question about the GIT_TOKEN. I noticed on line 17 of index.js you have a different process.env variable for your API key. We had previously defined gitToken on line 5. Shouldn't we be using that for our API calls instead of making separate environment variables? I'm totally happy to change line 5 to be process.env.GITHUB_TOKEN instead. It just seems like we would want to be consistent whatever it is. Unless I'm missing something. Let me know what you think.

Hey @carrjsn, I am sorry. I completely forgot about that. I have changed the env variable name on my local machine to be "GIT_API_TOKEN". Thanks for catching the error. 
And also I changed the grid-template-rows to be auto, so that the size of the rows will depend on the space a widget requires.

**Comment by carrjsn** [comment]
No worries! All looks great!

**Pull request merged**
